name: build and upload package to pypi

on:
  push:
    paths:
      - "common_packages/**"

jobs:
  deploy:
    name: build package
    runs-on: ubuntu-latest

    steps:
      - name: pull code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.2

      - name: Install poetry
        run: |
          pip install poetry && poetry config virtualenvs.create false

      - name: Install Dependencies
        run: poetry install

      - name: build package
        run: python -m build

      - name: create pypi config
        run: |
          echo "[pypi]" > ~/.pypirc
          echo "username = __token__" >> ~/.pypirc
          echo "password = ${{ secrets.PYPI_TOKEN}}" >> ~/.pypirc

      - name: upload package
        run: |
          && twine upload  dist/*
